version: "3.8"

services:
  db:
    image: postgres:15
    container_name: condominia_db
    environment:
      POSTGRES_USER: condominia
      POSTGRES_PASSWORD: condominia123
      POSTGRES_DB: condominio
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
